site_name: genesis dayrit's blog
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: black
      accent: purple
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: black
      accent: purple
  
plugins:
#   - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/genesisdayrit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_genesisdayrit
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/genesisdayrit/
  analytics:
    provider: google
    property: G-VB988S1KF3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/genesisdayrit"  target="_blank" rel="noopener">Genesis Dayrit</a>